In [2]:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import numpy as np
import tensorflow as tf

In [4]:
a = tf.constant(3.0, dtype=tf.float32)
b = tf.constant(2.0)
total = a + b

print(a)
print(b)
print(total)

Tensor("Const_2:0", shape=(), dtype=float32)
Tensor("Const_3:0", shape=(), dtype=float32)
Tensor("add_1:0", shape=(), dtype=float32)


In [5]:
sess = tf.Session()
print(sess.run(total))

5.0


In [7]:
print(sess.run({'total': total, 'ab' : (a, b)}))

{'total': 5.0, 'ab': (3.0, 2.0)}


In [10]:
vec = tf.random_uniform(shape=(3,))
out1 = vec + 1
out2 = vec + 2

print(sess.run(out1))
print(sess.run(out2))
print(sess.run((out1, out2)))

[1.6852362 1.7779399 1.4916567]
[2.6513734 2.4289904 2.85496  ]
(array([1.159081 , 1.4507346, 1.761232 ], dtype=float32), array([2.159081 , 2.4507346, 2.761232 ], dtype=float32))


In [14]:
x = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)
z = x + y

sess.run(z, feed_dict={x:4, y:2})
sess.run(z, feed_dict={x:[1,2], y:[3,0]})

array([4., 2.], dtype=float32)

In [22]:
my_data = [
    [0, 1,],
    [2, 3,],
    [4, 5,],
    [6, 7,],
]
slices = tf.data.Dataset.from_tensor_slices(my_data)
next_item = slices.make_one_shot_iterator().get_next()

while True:
    try:
        print(sess.run(next_item))
    except tf.errors.OutOfRangeError:
        break

[0 1]
[2 3]
[4 5]
[6 7]


In [28]:
x = tf.placeholder(tf.float32, shape=[None, 3])
linear_model = tf.layers.Dense(units=1)
y = linear_model(x)

In [32]:
init = tf.global_variables_initializer()
sess.run(init)

In [33]:
print(sess.run(y, {x: [[1, 2, 3],[4, 5, 6]]}))

[[ -4.193148]
 [-10.856297]]


In [39]:
# Define data
x = tf.constant([[1],[2],[3],[4]], dtype=tf.float32)
y_true = tf.constant([[0],[-1],[-2],[-3]], dtype=tf.float32)

# Define layer
linear_model = tf.layers.Dense(units=1)
y_pred = linear_model(x)

# Init parameter
init = tf.global_variables_initializer()

# Loss function
loss = tf.losses.mean_squared_error(labels=y_true, predictions=y_pred)

# Optimizer
optimizer = tf.train.GradientDescentOptimizer(0.01)
train = optimizer.minimize(loss)


# Run
sess = tf.Session()
sess.run(init)
for i in range(100):
    _, loss_value = sess.run((train, loss))
    print(loss_value)

2.5926857
1.8330902
1.3058192
0.9397543
0.68554825
0.50896037
0.38623056
0.30087334
0.24144913
0.20002057
0.17107984
0.15080547
0.13654564
0.12646027
0.11927264
0.114096805
0.110318065
0.10750984
0.105376124
0.10371159
0.10237371
0.10126356
0.10031251
0.09947293
0.098711796
0.098006144
0.09734008
0.096702516
0.09608579
0.09548451
0.094895065
0.09431481
0.09374198
0.093175314
0.09261391
0.09205721
0.091504715
0.090956196
0.090411395
0.08987016
0.08933234
0.088797905
0.08826677
0.08773888
0.087214194
0.086692676
0.08617428
0.085659035
0.08514687
0.08463777
0.0841317
0.0836287
0.08312869
0.082631655
0.08213763
0.081646554
0.081158385
0.08067316
0.080190815
0.07971139
0.079234764
0.078761056
0.07829016
0.07782207
0.077356756
0.07689428
0.07643453
0.07597756
0.07552329
0.075071745
0.07462291
0.074176736
0.07373324
0.07329242
0.07285421
0.07241863
0.071985655
0.071555264
0.071127445
0.07070219
0.070279464
0.06985928
0.06944159
0.06902643
0.06861372
0.0682035
0.067795694
0.067390375
0.0669874